### ISSUE TITLE
Loading packages that load packages from the standard library doesn't work

### ISSUE THREAD

**Issue by lewisl** [fonsp/Pluto.jl#1989]
```
ERROR: LoadError: ArgumentError: Package DataStructures not found in current path:
- Run `import Pkg; Pkg.add("DataStructures")` to install the DataStructures package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:967
 [2] include
   @ ./Base.jl:418 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1318
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:373 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:453
 [7] top-level scope
   @ none:1
in expression starting at /Users/lewis/Dropbox/Covid Modeling/Covid-ILM/source/CovidSim_ilm.jl:36
```

Results from the following in the loaded package:

```
__precompile__(true)

module CovidSim_ilm

# required
using DelimitedFiles
using DataStructures
using OrderedCollections
using OrderedCollections: FrozenLittleDict
using DataFrames
using CSV
using Random
using Distributions
using StatsBase
using Printf
using PrettyPrint
using Plots
using PlotThemes
using StatsPlots
using Dates
using YAML
using TypedTables
using SplitApplyCombine
using Interpolations


using Debugger

# ... lots more stuff: includes, definition of constants, exports

end
```

The Pluto notebook begins as:
```
# ╔═╡ 9d774e4e-57ea-41ca-96ab-1e67649f3571
push!(LOAD_PATH, joinpath(homedir(), "Dropbox/Covid Modeling/Covid-ILM/source"))

# ╔═╡ 0f10581a-02a6-4fb6-95df-9451149dc39f
using CovidSim_ilm
```

Interestingly, the DelimitedFiles package is found. But not the second package.  But, of course DataStructures is present in my Julia environment.

I get what you are trying to do about reproducibility. It is a hard problem.

But, my sense is that Pluto is meant for relatively simple things.  I'll stick to the ever reliable Jupyterlab. Except for teaching Julia--a very fine cause indeed--it's hard to see Pluto meeting the same needs that the Jupyter ecosystem can meet, with a lot more contributors. Of course, Jupyter is far from perfect as many people have noted.

This is not a real problem.  Having something light and quick that goes beyond what we do with the repl makes sense--especially being repeatable and self-documenting. And Jupyter is anything but light. 

Different use cases-->different solutions = Goodness

**Comment by icweaver** [comment]
Hi @lewisl, [this looks like](https://github.com/lewisl/Covidilmsim) a really useful package, thank you for sharing it!

I could be misunderstanding the issue you are running into, but after a few small tweaks it seems to work brilliantly for me in your [sample notebook](https://github.com/lewisl/Covidilmsim/blob/master/notebooks/test-ilm-pluto.jl):

![Screenshot from 2022-03-16 20-09-24](https://user-images.githubusercontent.com/25312320/158712208-7fbd453a-e63b-4130-94ab-16f43c2624cd.png)

I just did the following:
* renamed [`source`](https://github.com/lewisl/Covidilmsim/tree/master/source) to `src`
* added a Project.toml to the root directory (attached below)
* used `Pkg.activate` to use a [shared environment](https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#pattern-the-shared-environment) in Pluto
* removed `spreadcases` from `run_a_sim` above because it does not seem to be included in the [function signature here](https://github.com/lewisl/Covidilmsim/blob/3d5a512882baa4b4a071fe890e4d949ae671eac4/source/sim.jl#L7)

<details> <summary> Project.toml </summary>

```TOML
name = "CovidSim_ilm"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
```
</details>
